# Change these first
owner: aismartsheets # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: AI Smartsheets
    url: https://www.ai-sheets.com/
  - name: McNeely Dashboard
    url: http://20.165.38.39:8080/

notifications:
  - type: email
    NOTIFICATION_EMAIL: true
    NOTIFICATION_EMAIL_FROM: admin@aismartsheets.com
    NOTIFICATION_EMAIL_TO: admin@aismartsheets.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  favicon: https://raw.githubusercontent.com/aismartsheets/upptime/master/assets/favicon.png
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/aismartsheets/upptime/master/assets/ai-logo-v2.png
  name: "AI Smartsheets Status Page"
  introTitle: "AI Smartsheets website statuses"
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
